import { ChordSettings } from "./type"

export class MusicalConstants {
    static readonly CHORD_SETTINGS_INIT: ChordSettings = {
        _sharp: {isTrue: false, text: "#"},
        _flat: {isTrue: false, text: "b"},
        _root: {isTrue: false, text: "R"},
        _power: {isTrue: false, text: "5"},
        _M: {isTrue: false, text: "M"},
        _m: {isTrue: false, text: "m"},
        _dim: {isTrue: false, text: "dim"},
        _aug: {isTrue: false, text: "aug"},
        _sus2: {isTrue: false, text: "sus2"},
        _sus4: {isTrue: false, text: "sus4"},
        _6: {isTrue: false, text: "6"},
        _m6: {isTrue: false, text: "m6"},
        _7: {isTrue: false, text: "7"},
        _M7: {isTrue: false, text: "M7"},
        _m7: {isTrue: false, text: "m7"},
        _mM7: {isTrue: false, text: "mM7"},
        _aug7: {isTrue: false, text: "aug7"},
        _dim7: {isTrue: false, text: "dim7"},
        _7b5: {isTrue: false, text: "7(b5)"},
        _7shp5: {isTrue: false, text: "7(#5)"},
        _m7b5: {isTrue: false, text: "m7(b5)"},
        _m7shp5: {isTrue: false, text: "m7(#5)"},
    }

    static readonly CHORD = {
        _root: [1],
        _power: [1, 5],
        _M: [1, 5, 8],
        _m: [1, 4, 8],
        _dim: [1, 4, 7],
        _aug: [1, 5, 9],
        _sus2: [1, 3, 8],
        _sus4: [1, 6, 8],
        _6: [1, 5, 8, 10],
        _m6: [1, 5, 8, 10],
        _7: [1, 5, 8, 11],
        _M7: [1, 5, 8, 12],
        _m7: [1, 5, 8, 11],
        _mM7: [1, 5, 8, 12],
        _aug7: [1, 5, 9, 11],
        _dim7: [1, 4, 7, 10],
        _7b5: [1, 5, 7, 11],
        _7shp5: [1, 5, 9, 11],
        _m7b5: [1, 4, 7, 11],
        _m7shp5: [1, 4, 9, 11],
    }
}